apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
spec:
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
        db: in-memory
    spec:
      containers:
      - name: cart
        image: eyujy/cart:1.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            cpu: "200m"
            memory: "64Mi"  
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"  
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: user
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: password   
        ports:
          - containerPort: 80
 
---
apiVersion: v1
kind: Service
metadata:
  name: cart
spec:
  type: NodePort
  selector:
    app: cart
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001

# ---
# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: cart
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: cart
#   minReplicas: 1
#   maxReplicas: 10
#   targetCPUUtilizationPercentage: 50

# kubectl run -i --tty load-generator --rm --image=busybox --restart=Never -- /bin/sh -c "while sleep 0.01; do wget -q -O- http://cart; done"